import Link from 'next/link'
import { Shield } from 'lucide-react'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 bg-white/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Shield className="w-6 h-6 text-blue-600" />
            <span className="font-bold text-gray-900 text-lg">VaultCheck</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: March 21, 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-sm leading-relaxed text-gray-600">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Overview</h2>
            <p>
              VaultCheck (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) respects your privacy and is committed to protecting the data you share with us. This Privacy Policy describes how we collect, use, store, and protect your information when you use our payment verification assistance service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Information We Collect</h2>
            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Account Information</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li>Name, email address, and firm name (provided during signup)</li>
              <li>Authentication data managed by Supabase Auth (session tokens)</li>
              <li>Billing information processed by Stripe (we do not store credit card numbers)</li>
            </ul>

            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">QuickBooks Online Data</h3>
            <p>When you connect a QuickBooks Online account, we access and store:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>Vendor information:</strong> Display name, company name, email address, phone number</li>
              <li><strong>Bill (invoice) data:</strong> Invoice numbers, amounts, due dates, currency</li>
              <li><strong>Bill payment data:</strong> Payment amounts, dates, payment methods</li>
              <li><strong>OAuth tokens:</strong> Access and refresh tokens for API access (encrypted at rest)</li>
            </ul>
            <p className="mt-2">We access QuickBooks data in <strong>read-only mode</strong>. We do not create, modify, or delete any records in your QuickBooks account.</p>

            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Derived Data</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Vendor fingerprints:</strong> Statistical profiles (average amounts, frequency, known email domains) computed from payment history</li>
              <li><strong>Risk scores:</strong> Numerical scores (0-100) computed for each invoice</li>
              <li><strong>Alerts:</strong> Flagged anomalies generated by our scanning engine</li>
              <li><strong>Audit logs:</strong> Records of all scans, decisions, and data access</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. How We Protect Your Data</h2>
            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Encryption</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li>QuickBooks OAuth tokens are encrypted at rest using AES-256-GCM</li>
              <li>All data in transit is encrypted via TLS 1.2+</li>
              <li>Database connections use SSL</li>
            </ul>

            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Bank Account Data</h3>
            <p>
              <strong>We never store raw bank account numbers.</strong> When bank account information is encountered (e.g., on vendor invoices), we store only a salted SHA-256 hash of the last 4 digits combined with the routing number. This allows us to detect changes without storing sensitive financial data.
            </p>

            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Multi-Tenant Isolation</h3>
            <p>
              All data is scoped to your firm. Row-level security policies ensure that users can only access data belonging to their own firm. Cross-firm data access is technically impossible through the application layer.
            </p>

            <h3 className="text-base font-medium text-gray-800 mt-4 mb-2">Logging</h3>
            <p>
              We never log full bank account numbers, social security numbers, or authentication tokens. Logs contain only masked or hashed identifiers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. How We Use Your Data</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To build vendor fingerprints and compute invoice risk scores</li>
              <li>To generate alerts when anomalies are detected</li>
              <li>To send email notifications about flagged invoices and weekly reports</li>
              <li>To generate PDF reports summarizing scanning activity</li>
              <li>To maintain audit trails for compliance purposes</li>
              <li>To improve the accuracy of our anomaly detection algorithms</li>
            </ul>
            <p className="mt-2">We do not sell your data to third parties. We do not use your data for advertising.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Third-Party Services</h2>
            <p>We use the following third-party services to provide the Service:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>Supabase:</strong> Authentication and database hosting (PostgreSQL)</li>
              <li><strong>Vercel:</strong> Application hosting and deployment</li>
              <li><strong>Stripe:</strong> Payment processing (PCI-compliant)</li>
              <li><strong>Resend:</strong> Transactional email delivery</li>
              <li><strong>Upstash:</strong> Redis for background job queues</li>
              <li><strong>Sentry:</strong> Error monitoring (no sensitive data is sent)</li>
              <li><strong>Intuit/QuickBooks:</strong> Accounting data access via OAuth 2.0</li>
            </ul>
            <p className="mt-2">Each third-party provider operates under their own privacy policy and data processing agreements.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Data Retention</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Account data is retained for as long as your account is active</li>
              <li>QuickBooks data is synced and retained to maintain vendor fingerprints and audit trails</li>
              <li>Audit logs are retained for 24 months</li>
              <li>Upon account deletion, all associated data is permanently deleted within 30 days</li>
              <li>QuickBooks OAuth tokens are revoked and deleted upon disconnection</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Your Rights</h2>
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>Access</strong> the data we store about you and your firm</li>
              <li><strong>Disconnect</strong> QuickBooks integration at any time</li>
              <li><strong>Delete</strong> your account and all associated data</li>
              <li><strong>Export</strong> your data in standard formats</li>
              <li><strong>Revoke</strong> QuickBooks access through your Intuit account settings</li>
            </ul>
            <p className="mt-2">To exercise these rights, contact us at <strong>privacy@vaultcheck.app</strong>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Cookies</h2>
            <p>
              We use essential cookies for authentication session management. We do not use tracking cookies, analytics cookies, or advertising cookies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of material changes via email or through the Service. Your continued use of the Service after changes take effect constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">10. Contact</h2>
            <p>
              For questions about this Privacy Policy, contact us at <strong>privacy@vaultcheck.app</strong>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
